Various GitLab improvements (files, better retrieval of trees, import_limit, faster overview, regex for filtering branches, ...)
mantisbt-plugins/source-integration pull request #342
Opened 2020-07-27 16:29 UTC by being-peace

* list filenames to changesets
  * support more than one parent when grabbing repositories
  * put import_limit as configurable option
  * making counting of files in the overview optional, because it may take long on large repositories
  * add regexp or list filtering of branches
  * make import_limit work (as import_latest is called repeatedly)

2020-07-28 07:06 UTC, dregad commented
@being-peace many thanks for your contribution. 

If it's not too much effort, I would greatly appreciate if you could split your commit into atomic changes (i.e. each one of the above bullet points should be a distinct commit).

Also, considering that the SourceGithub plugin has a very similar code base (Gitlab was initially created as a clone of it), it would be great to see of some or all of your proposed enhancements, could also apply to it.

2020-07-28 08:39 UTC, being-peace commented
Puh, of course, atomic changes would be cleaner, but indeed, it's quite an effort. I don't know, when I find time for this. Technically, it would mean creating new pull requests for each of the contributions? Or is there a different way?

Regarding GitHub, there are things that I could add (add regexp or list filtering of branches), but others (in most importantly, the files) are already in GitHub.

2020-07-28 10:48 UTC, dregad commented
> atomic changes would be cleaner, but indeed, it's quite an effort

Grouped changes makes the review / testing process more difficult and time-consuming for me (and I don't have a lot of spare time :wink: ). 

It can remain a single pull request with multiple commits submitted from a single feature branch, or split into several PR's as you prefer, it makes no difference for me. Note: this is where logging Issues separately can be useful, as you can reference issues in the commit message (e.g. _Fixes #xxx_) and when the PR is merged, all corresponding issues will be closed automatically.

If it's too much work I could merge as-is of course, but please keep in mind to make atomic commits in the future.

> Regarding GitHub, there are things that I could add (add regexp or list filtering of branches), but others (in most importantly, the files) are already in GitHub.

Thanks for looking into it.

2021-01-23 13:50 UTC, dregad requested changes
@being-peace I started looking into merging this. Here's my review:

You're (re-)introducing calls to deprecated APIs: *helper_alternate_class()* calls were removed back in 2017 (release 1.3.2), see 3d29ee674a9ff9a1ad4d8e49cb12e866e9642d88 and *db_query_bound()*.

The _disable file stats_ option is global, so it definitely shouldn't be hidden within a GitLab-specific PR. I'll create a separate issue to track this feature, and since you said you didn't want to do this, I'll extract the code myself (shouldn't take more than 5 minutes...) and fix separately; note that this will take care of the deprecated db_query_bound() call mentioned above.

The _regex branches filter_ feature I definitely want to see applied to all Git-based plugins, not just GitLab. Please refactor accordingly, and submit as a separate PR.

I'm getting a *String "plugin_Source_error_invalid_branch_regexp" not found* warning when initializing the plugin. And please use `regex` instead of `regexp` for the string's name, to be consisten with usage of this term elsewhere in the plugin.

As for the rest, following recent commits to master, there are now several merge conflicts, so I'll kindly ask you to sort those out and resubmit.

Thanks

2021-01-25 21:51 UTC, being-peace commented
@dregad  Thanks for having a look, the comments and submitting the "file count" seperately. You are definitely right with your comments. 

I would like to find some time to resolve the other things, but I cannot promise... :-(

2021-01-26 10:00 UTC, dregad commented
OK, thanks. Take your time :smiley:

2021-12-30 15:16 UTC, dregad commented
@being-peace considering it's been almost a year without activity, and the PR has conflicts, I'm going to close it for now. Feel free to reopen after rebasing your branch, or create a new PR if and when you're ready.

2021-12-30 15:16 UTC, closed without merging